site_name: uPython
nav:
  - 'Документация': index.md
  - '&#128640; Руководство':
    - 'Начало работы': guide/cpy_start.md
    - 'Сборка CircuitPython': guide/cpy_building.md
  - '&#128036; TinyML':
    - 'Обзор': tinyml/review.md
    - 'TFLite Micro': tinyml/tflite.md
    - 'Edge Impulse' : tinyml/edge_impulse.md
  - '&#128218; Справочник':
    - 'CircuitPython': ref/cpy.md
    - 'ESP-IDF': ref/esp_idf.md
    - 'API Helpers': ref/api_helpers.md
  - '&#128295; Рецепты':
    - 'OneWire': howto/onewire.md

theme:
  name: readthedocs
# name: mkdocs
  highlightjs: true
  locale: ru
plugins:
#  - with-pdf:
#      author: akhud78
#      copyright: Navtelecom
#      cover_subtitle: версия 0.1
#      toc_title: Содержание
#      output_path: upython.pdf
  - search:
      lang: ['en']
  - autorefs
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
#  - pymdownx.highlight:
#      anchor_linenums: true
#      line_spans: __span
#      pygments_lang_class: true
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
#  - pymdownx.superfences

