site_name: uPython
nav:
  - 'uPython': index.md
  - 'Руководство': tutorial.md
  - 'Thonny': thonny.md
  - 'Сборка': building.md
  - 'ESP32-S3': esp32-s3.md
  - 'API': api.md
theme:
  name: readthedocs
# name: mkdocs
  highlightjs: true
  locale: ru
plugins:
#  - with-pdf:
#      author: akhud78
#      copyright: Navtelecom
#      cover_subtitle: версия 0.1
#      toc_title: Содержание
#      output_path: upython.pdf
  - search:
      lang: ['en']
  - autorefs
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
#  - pymdownx.highlight:
#      anchor_linenums: true
#      line_spans: __span
#      pygments_lang_class: true
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
#  - pymdownx.superfences

